export const INFO_FETCH_FAILED = 'INFO_FETCH_FAILED';
export const INFO_FETCH_LOADING="INFO_FETCH_LOADING";
export const INFO_FETCH_SUCCESS = 'INFO_FETCH_SUCCESS';

export const SCHEDULE_FETCH_FAILED = 'SCHEDULE_FETCH_FAILED';
export const SCHEDULE_FETCH_LOADING = "SCHEDULE_FETCH_LOADING";
export const SCHEDULE_FETCH_SUCCESS = 'SCHEDULE_FETCH_SUCCESS';
