export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';
export const DATA_FETCH_LOADING="DATA_FETCH_LOADING";
export const SCHEDULE_FETCH_SUCCESS = 'SCHEDULE_FETCH_SUCCESS';
export const INFO_FETCH_SUCCESS = 'INFO_FETCH_SUCCESS';