export const COURSE_FETCH_FAILED = 'COURSE_FETCH_FAILED';
export const COURSE_FETCH_SUCCESS = 'COURSE_FETCH_SUCCESS';
export const SCHEDULE_FETCH_FAILED = 'SCHEDULE_FETCH_FAILED';
export const SCHEDULE_FETCH_SUCCESS = 'SCHEDULE_FETCH_SUCCESS';