# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: gh pages publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: publish package
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm i
          npm i -g @layer0/cli
          echo ${{secrets.FIRE_CONFIG}} > src/config/fire.json
          npm run build
          layer0 deploy  --token=${{secrets.layer0DeployToken}}
