# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: gh pages publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: publish package
        run: |
          npm i
          git config user.name "itissandeep98"
          git config user.email "itissandeep98@gmail.com"
          echo ${{secrets.FIRE_CONFIG}} > src/config/fire.json
          git remote set-url origin https://itissandeep98:${{secrets.ACCESS_TOKEN}}@github.com/itissandeep98/TimeTableManager
          npm run deploy
